### ISSUE TITLE
PkHex latest version won't load with this plugin installed

### ISSUE THREAD

**Issue by javierhimura** [DarkKrimson/PKHeX-Sprite-Plugin#1]
Something that has been changed on latest PkHex release has made this plugin incompatible.
PkHex won't load with this plugin installed anymore.

![imagen](https://user-images.githubusercontent.com/21158487/215269740-143a4bba-3a8c-4970-b1ac-a8e858d43906.png)

Exception Details:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotSupportedException: Cannot read resources that depend on serialization.
   at System.Resources.ResourceReader.DeserializeObject(Int32 typeIndex)
   at System.Resources.ResourceReader.LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.RuntimeResourceSet.ReadValue(ResourceReader reader, Int32 dataPos, Boolean isString, ResourceLocator& locator)
   at System.Resources.RuntimeResourceSet.GetObject(String key, Boolean ignoreCase, Boolean isString)
   at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture, Boolean wrapUnmanagedMemStream)
   at PKHeX.Drawing.PokeSprite.SpriteBuilder.GetBaseImageDefault(UInt16 species, Byte form, Int32 gender, UInt32 formarg, Boolean shiny, EntityContext context)
   at PKHeX.Drawing.PokeSprite.SpriteBuilder.GetBaseImage(UInt16 species, Byte form, Int32 gender, UInt32 formarg, Boolean shiny, EntityContext context)
   at PKHeX.Drawing.PokeSprite.SpriteBuilder.GetSprite(UInt16 species, Byte form, Int32 gender, UInt32 formarg, Int32 heldItem, Boolean isEgg, Shiny shiny, EntityContext context, SpriteBuilderTweak tweak)
   at PKHeX.Drawing.PokeSprite.SpriteUtil.GetSprite(PKM pk, SpriteBuilderTweak tweak)
   at PKHeX.Drawing.PokeSprite.SpriteUtil.GetSprite(PKM pk, SaveFile sav, Int32 box, Int32 slot, Boolean flagIllegal)
   at PKHeX.WinForms.Main.GetPreview(PictureBox pb, PKM pk)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at DarkKrimsonSpritePack.DarkKrimsonSpritePlugin.Initialize(Object[] args)
   at PKHeX.WinForms.Main.FormLoadPlugins()
   at PKHeX.WinForms.Main..ctor()
   at PKHeX.WinForms.Program.Main()

**Comment by DarkKrimson** [comment]
PKHeX has update to use NET 7.0. This plugin only works with versions of PKHeX that were built in NET 4.6.

**Comment by n-jones0** [comment]
Are there any plans to update the plugin for .NET 7? Even if someone wanted to revert to an older .NET 4 version for compatibility, old versions of PKHeX are not available for download.
